# tool/src/schema.py
REQUIRED = {
    "clienti_clusterizzati.csv": [
        "codice_cliente",
        "cluster",
        "persona_label",
        "cluster_risposta",
        "engagement_score",
        "satisfaction_score",
        "reclami_totali",
        "clv_stimato",
        "potenziale_crescita",
        "luogo_di_residenza",
        "zona_di_residenza",
    ],
    "potential_score_comuni.csv": [
        "luogo_di_residenza",
        "n_clienti",
        "lat",
        "lon",
        "potential_score_casa",
        "potential_score_salute",
        "protection_gap_casa",
        "protection_gap_salute",
        "valore_immobiliare_medio",
        "NDVI_mean",
    ],
    "nba_scores_clienti.csv": [
        "codice_cliente",
        "next_best_action",
        "priority_score",
        "nba_reason",
        "churn_score_model",
        "cross_sell_score",
        "clv_stimato",
        "potenziale_crescita",
        "engagement_score",
        "satisfaction_score",
        "reclami_totali",
        "mesi_da_ultima_visita",
        "multi_polizza_flag",
        "valore_atteso_euro",
    ],
    "pricing_ai_output.csv": [
        "codice_cliente",
        "prodotto",
        "premio_totale_annuo",
        "premio_simulato",
        "p_claim",
        "severity_pred",
        "pure_premium_pred",
        "loss_ratio_pred",
        "loss_ratio_post",
        "cluster_stream1",
        "cluster_risposta",
        "pricing_action",
    ],
}
